services:
  backend:
    image: technocracynitrr/dig-cert-nitrr-backend:latest
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./backend_access.log:/backend/backend_access.log
      - ./backend_error.log:/backend/backend_error.log
      - ./events_db:/backend/events_db
      - ./signed_certificates:/backend/signed_certificates
    command: bash -c "python manage.py migrate &&
                      python -m gunicorn -w 4 backend.wsgi:application --bin 0.0.0.0:8000 --access-logfile backend_access.log --error-logfile backend_error.log"
    env_file:
      - .env
    depends_on:
      - db
  # frontend:
  #   image: piyushthedock/dig-cert-nitrr-frontend:latest
  #   restart: always
  #   ports:
  #     - "3000:3000"
  #   command: >
  #     bash -c "cp -rfu /cache/node_modules/. /frontend/node_modules/
  #     && npm start"
  #   depends_on:
  #     - backend
  #   environment:
  #     - WATCHPACK_POLLING=true

  db:
    image: postgres
    volumes:
      - ./db:/var/lib/postgresql/data
    env_file:
      - .env
  nginx:
    image: technocracynitrr/dig-cert-nitrr-nginx
    ports:
      - "8080:80"
  redis:
    image: redis:latest

  celery_worker:
    image: technocracynitrr/dig-cert-nitrr-backend:latest
    depends_on:
      - redis
      - backend
    environment:
      - C_FORCE_ROOT=true
      - CELERY_BROKER=redis://redis:6379/0
    command: python -m celery -A main.tasks worker --loglevel=DEBUG

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: always
    environment:
        - IN=Asia/Calcutta
        - WATCHTOWER_DEBUG=true
        - WATCHTOWER_CLEANUP=true
        - WATCHTOWER_POLL_INTERVAL=120
        - WATCHTOWER_INCLUDE_RESTARTING=true
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
        - backend
        - nginx
        - db
        - celery_worker
        - redis
